# Generated by Django 4.0.8 on 2023-05-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
