# Generated by Django 4.0.8 on 2023-05-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0004_remove_course_subjects_subject'),
        ('management', '0004_delete_studentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authman.subject'),
        ),
    ]
