# Generated by Django 4.0.8 on 2023-05-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_attendance_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='student',
        ),
        migrations.DeleteModel(
            name='LeaveReportStaff',
        ),
        migrations.DeleteModel(
            name='LeaveReportStudent',
        ),
    ]
