# Generated by Django 4.0.8 on 2023-05-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='staff',
        ),
    ]
