# Generated by Django 4.2.1 on 2023-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role_number',
            field=models.CharField(default='001', help_text='staff unique identifier', max_length=10, unique=True),
        ),
    ]
