# Generated by Django 4.0.8 on 2023-05-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_code'),
        ('authman', '0002_staff_course_alter_staff_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(to='academics.subject'),
        ),
    ]
