# Generated by Django 4.2.1 on 2023-06-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0002_staff_role_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role_number',
            field=models.CharField(help_text='staff unique identifier', max_length=10, unique=True),
        ),
    ]
