# Generated by Django 4.0.8 on 2023-05-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0004_remove_course_subjects_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['sirname', 'firstname', 'other_name']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='surname',
            new_name='sirname',
        ),
    ]
