# Generated by Django 4.0.8 on 2023-05-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0005_alter_student_options_rename_surname_student_sirname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id', 'current_class']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sirname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
