# Generated by Django 4.0.8 on 2023-05-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0009_student_current_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kcpe_entry_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
