# Generated by Django 4.0.8 on 2023-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='apply_for_all_students',
            field=models.BooleanField(default=False),
        ),
    ]
