# Generated by Django 4.0.8 on 2023-05-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_apply_for_all_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Deposit'), ('cash', 'Cash'), ('mobile', 'Mobile Money')], default='Bank Deposit', max_length=50),
        ),
    ]
