# Generated by Django 4.0.8 on 2023-05-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authman', '0008_remove_student_parent_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Grades',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GradingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='authman.course')),
                ('grade', models.ForeignKey(default='A', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.grades')),
            ],
            options={
                'verbose_name_plural': 'Grading Rules',
                'ordering': ['mark', 'grade'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GradingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('highschool', 'Highschool'), ('college', 'College'), ('university', 'University')], max_length=100)),
                ('grading_rules', models.ManyToManyField(to='grading.gradingrules')),
            ],
            options={
                'verbose_name_plural': 'Grading Levels',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
