# Generated by Django 4.0.8 on 2023-05-24 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=2)),
                ('points', models.IntegerField(default=1)),
                ('comment', models.TextField(default='Pass', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Grades',
                'ordering': ['name', 'comment'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GradingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('highschool', 'Highschool'), ('college', 'College'), ('university', 'University')], max_length=100)),
                ('current', models.BooleanField(blank=True, default=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='authman.course')),
            ],
            options={
                'verbose_name_plural': 'Grading Levels',
                'ordering': ['name', 'course'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OverallGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('highschool', 'Highschool'), ('college', 'College'), ('university', 'University')], default='highschool', max_length=100)),
                ('current', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Overall Grading',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OveralGradingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_range', models.CharField(default='0-0', max_length=10)),
                ('points_range', models.CharField(default='0-0', max_length=10)),
                ('grade', models.ForeignKey(default='A', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.grades')),
                ('overall_grading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradingitems', to='grading.overallgrading')),
            ],
            options={
                'verbose_name_plural': 'Overall Grading Rules',
                'ordering': ['mark_range', 'points_range', 'grade'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GradingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_range', models.CharField(default='0-0', max_length=10)),
                ('grade', models.ForeignKey(default='A', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.grades')),
                ('grading_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_rules', to='grading.gradinglevel')),
            ],
            options={
                'verbose_name_plural': 'Grading Rules',
                'ordering': ['mark_range', 'grade'],
                'managed': True,
            },
        ),
    ]
