# Generated by Django 4.0.8 on 2023-05-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradinglevel',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
