# Generated by Django 4.0.8 on 2023-05-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_remove_gradinglevel_grading_rules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingrules',
            name='grading_level',
        ),
        migrations.AddField(
            model_name='gradingrules',
            name='grading_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grading_rules', to='grading.gradinglevel'),
            preserve_default=False,
        ),
    ]
