# Generated by Django 4.0.8 on 2023-05-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_remove_gradingrules_grading_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'managed': True, 'ordering': ['name', 'comment'], 'verbose_name_plural': 'Grades'},
        ),
        migrations.AddField(
            model_name='grades',
            name='comment',
            field=models.CharField(default='Pass', max_length=2),
        ),
    ]
