# Generated by Django 4.0.8 on 2023-05-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_alter_grades_options_grades_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='points',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
