# Generated by Django 4.0.8 on 2023-05-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_alter_grades_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='comment',
            field=models.TextField(default='Pass', max_length=255),
        ),
    ]
