# Generated by Django 4.0.8 on 2023-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_alter_grades_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingrules',
            options={'managed': True, 'ordering': ['mark_range', 'grade'], 'verbose_name_plural': 'Grading Rules'},
        ),
        migrations.RemoveField(
            model_name='gradingrules',
            name='mark',
        ),
        migrations.AddField(
            model_name='gradingrules',
            name='mark_range',
            field=models.CharField(default='0-0', max_length=10),
        ),
        migrations.AlterField(
            model_name='gradinglevel',
            name='current',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
