# Generated by Django 4.0.8 on 2023-05-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0008_remove_student_parent_mobile_number_and_more'),
        ('grading', '0009_alter_gradingrules_options_remove_gradingrules_mark_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradinglevel',
            options={'managed': True, 'ordering': ['name', 'course'], 'verbose_name_plural': 'Grading Levels'},
        ),
        migrations.RemoveField(
            model_name='gradingrules',
            name='course',
        ),
        migrations.AddField(
            model_name='gradinglevel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='authman.course'),
        ),
    ]
