# Generated by Django 4.0.8 on 2023-05-21 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0010_alter_gradinglevel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OveralGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_range', models.CharField(default='0-0', max_length=10)),
                ('grade', models.ForeignKey(default='A', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.grades')),
                ('grading_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_grading', to='grading.gradinglevel')),
            ],
            options={
                'verbose_name_plural': 'Overall Grading Rules',
                'ordering': ['mark_range', 'grade'],
                'managed': True,
            },
        ),
    ]
