# Generated by Django 4.0.8 on 2023-05-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0011_overalgrading'),
    ]

    operations = [
        migrations.AddField(
            model_name='overalgrading',
            name='points_range_range',
            field=models.CharField(default='0-0', max_length=10),
        ),
    ]
