# Generated by Django 4.0.8 on 2023-05-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0012_overalgrading_points_range_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='OveralGradingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_range', models.CharField(default='0-0', max_length=10)),
                ('points_range_range', models.CharField(default='0-0', max_length=10)),
                ('grade', models.ForeignKey(default='A', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.grades')),
            ],
            options={
                'verbose_name_plural': 'Overall Grading Rules',
                'ordering': ['mark_range', 'points_range_range', 'grade'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OverallGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('highschool', 'Highschool'), ('college', 'College'), ('university', 'University')], max_length=100)),
                ('current', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Overall Grading',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='OveralGrading',
        ),
        migrations.AddField(
            model_name='overalgradingitem',
            name='overall_grading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradingitems', to='grading.overallgrading'),
        ),
    ]
