# Generated by Django 4.0.8 on 2023-05-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0013_overalgradingitem_overallgrading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overalgradingitem',
            options={'managed': True, 'ordering': ['mark_range', 'points_range', 'grade'], 'verbose_name_plural': 'Overall Grading Rules'},
        ),
        migrations.RenameField(
            model_name='overalgradingitem',
            old_name='points_range_range',
            new_name='points_range',
        ),
        migrations.AlterField(
            model_name='overallgrading',
            name='name',
            field=models.CharField(choices=[('highschool', 'Highschool'), ('college', 'College'), ('university', 'University')], default='highschool', max_length=100),
        ),
    ]
