# Generated by Django 4.2.1 on 2023-06-02 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('Stime', models.TimeField(help_text='Starting time')),
                ('Etime', models.TimeField(help_text='Ending time')),
                ('Day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=3)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authman.staff')),
            ],
        ),
    ]
