# Generated by Django 4.2.1 on 2023-06-03 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_creattable_stream_creattable_table_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creattable',
            options={'verbose_name_plural': 'Manage Timetable'},
        ),
        migrations.RemoveField(
            model_name='creattable',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='creattable',
            name='table_class',
        ),
    ]
