# Generated by Django 4.2.1 on 2023-06-03 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('timetable', '0003_alter_creattable_options_remove_creattable_stream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creattable',
            name='Class',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creattable',
            name='stream',
            field=models.ManyToManyField(to='academics.classsection'),
        ),
    ]
