# Generated by Django 4.2.1 on 2023-06-03 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_creattable_class_creattable_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creattable',
            name='stream',
        ),
        migrations.AddField(
            model_name='creattable',
            name='stream',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
