# Generated by Django 4.2.1 on 2023-06-04 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('timetable', '0005_remove_creattable_stream_creattable_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creattable',
            name='Class',
        ),
        migrations.AddField(
            model_name='creattable',
            name='table_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.studentclass'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='creattable',
            name='stream',
        ),
        migrations.AddField(
            model_name='creattable',
            name='stream',
            field=models.ManyToManyField(to='academics.classsection'),
        ),
    ]
