# Generated by Django 4.2.1 on 2023-06-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_studentclass_sections'),
        ('authman', '0001_initial'),
        ('timetable', '0006_remove_creattable_class_creattable_table_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creattable',
            name='stream',
        ),
        migrations.AlterField(
            model_name='creattable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authman.subject'),
        ),
        migrations.AddField(
            model_name='creattable',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.classsection'),
            preserve_default=False,
        ),
    ]
