# Generated by Django 4.2.1 on 2023-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='sections',
            field=models.ManyToManyField(blank=True, null=True, to='academics.classsection'),
        ),
    ]
