# Generated by Django 4.0.8 on 2023-05-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0002_alter_result_subject'),
        ('management', '0005_alter_attendance_subject'),
        ('authman', '0004_remove_course_subjects_subject'),
        ('academics', '0002_subject_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
