# Generated by Django 4.2.1 on 2023-06-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_studentclass_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='sections',
            field=models.ManyToManyField(help_text='Select Custom if class ha no sections', to='academics.classsection'),
        ),
    ]
