# Generated by Django 4.0.8 on 2023-05-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_delete_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='section',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='section',
            field=models.ManyToManyField(to='academics.classsection'),
        ),
    ]
