# Generated by Django 4.0.8 on 2023-05-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_studentclass_section_studentclass_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclass',
            old_name='section',
            new_name='sections',
        ),
    ]
