# Generated by Django 4.0.8 on 2023-05-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_rename_section_studentclass_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(default='school_logo/default.png', upload_to='school_logo/'),
        ),
    ]
