# Generated by Django 4.0.8 on 2023-05-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_siteconfig_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='school_logo/default.png', upload_to='school_logo/')),
            ],
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='logo',
        ),
    ]
