# Generated by Django 4.2.1 on 2023-05-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_schoolsetup_remove_siteconfig_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolsetup',
            options={'verbose_name_plural': 'School Setup'},
        ),
    ]
