# Generated by Django 4.0.8 on 2023-05-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_schoolsetup_remove_siteconfig_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolsetup',
            options={'verbose_name_plural': 'School Setup'},
        ),
        migrations.AlterField(
            model_name='classsection',
            name='name',
            field=models.CharField(default='Custom', max_length=200),
        ),
    ]
