# Generated by Django 4.0.8 on 2023-05-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_schoolsetup_options_alter_classsection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
